### ISSUE TITLE
rules_proto release build fails with wrong bazel-cache

### ISSUE THREAD

**Issue by meteorcloudy** [bazel-contrib/.github#16]
https://github.com/bazelbuild/rules_proto/actions/runs/9520256013/job/26245280441

```
ERROR: error loading package under directory '': error loading package '~/.cache/bazel-repo/bazel/_bazel_runner/43914acf8bee29fb1d82f3e3dee22a49/external/bazel_tools/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper': Unable to find package for @@[unknown repo 'rules_java' requested from @@]//java:defs.bzl: The repository '@@[unknown repo 'rules_java' requested from @@]' could not be resolved: No repository visible as '@rules_java' from main repository.

```

This error is not reproducible locally from rules_proto @ https://github.com/bazelbuild/rules_proto/commit/8df2b708c484ba24f95069b3deeb94d38b50f32a

The previous run was with 7.1.1 and this one is with Bazel 7.2.0, therefore I suspect the wrong cache was used in the build.

**Comment by meteorcloudy** [comment]
@alexeagle Does my assumption make any sense?

**Comment by meteorcloudy** [comment]
Maybe it's related to https://github.com/bazelbuild/bazel/issues/16937 where `XDG_CACHE_HOME` is now respected by Bazel.

**Comment by meteorcloudy** [comment]
https://github.com/bazel-contrib/.github/blob/b134b73fcae522bc77dcc03533d3de20b45714bf/.github/workflows/release_ruleset.yaml#L40-L41

Looks like `XDG_CACHE_HOME` was only meant for Bazelisk previously.

**Comment by alexeagle** [comment]
Ah nice! Thanks for tracking that down.

**Comment by alexeagle** [comment]
https://github.com/bazel-contrib/.github/pull/13/files fixed this by switching this reusable workflow to use https://github.com/bazel-contrib/setup-bazel

rules_proto is still on v5 of this repo, so it missed that upgrade https://github.com/bazel-contrib/.github/compare/v5...v6

I'll update rules_proto and also check why it isn't getting regular updates from Renovate.
